"""empty message

Revision ID: 871a10fef2b1
Revises: 
Create Date: 2017-01-10 15:48:51.691682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871a10fef2b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('imagecap', sa.String(length=100), nullable=True),
    sa.Column('banner', sa.String(length=100), nullable=True),
    sa.Column('author', sa.SmallInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('short', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('isvisible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('articletag',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('articleid', sa.SmallInteger(), nullable=True),
    sa.Column('tag', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('author',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('displayname', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('blog',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('config',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('articlesperpage', sa.SmallInteger(), nullable=True),
    sa.Column('blogname', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    op.drop_table('blog')
    op.drop_table('author')
    op.drop_table('articletag')
    op.drop_table('article')
    # ### end Alembic commands ###
